// Homatri 30-Day Content Challenge — shot lists for home chefs.
// Patterned on how small-food-business creators grow on Instagram:
// document the build (origin → craft → trust → community), food beauty,
// process transparency, and interactive hooks. Each day is one reel;
// the chef only SHOOTS the raw clips + voice note — the Homatri team
// edits and posts the final reel.

export const CONTENT_PLAN = [
  {
    day: 1,
    title: "Namaskar — meet your new favourite kitchen",
    hook: "Ghansoli mein ek naya kitchen shuru hua hai… mera apna ghar ka.",
    why: "Introductions first — people order from people, not menus.",
    scenes: [
      { shot: "You at the door of your home, waving and smiling", how: "Selfie angle, natural light, 5 sec", secs: 5 },
      { shot: "Quick pan from door to kitchen", how: "Walk with the phone, keep it steady", secs: 4 },
      { shot: "You tying your apron / switching on the stove", how: "Close-up on hands", secs: 4 },
      { shot: "One smiling look into the camera", how: "Hold still, big smile", secs: 3 },
    ],
    voice: [
      "Namaskar! Main hoon [your name], aur yeh hai [kitchen name].",
      "Ghar ka khana, ghar ki tarah — sirf aapke liye.",
      "Aaj se shuru ho raha hai humara safar… chaliye saath chalte hain!",
    ],
    cta: "Follow to watch me build my tiffin business from my own kitchen.",
  },
  {
    day: 2,
    title: "Why I started cooking for my neighbourhood",
    hook: "Log kehte the mera khana restaurant se accha hai… toh kyun nahi main hi khilaun?",
    why: "Origin story = the strongest hook in the 'documenting the build' genre.",
    scenes: [
      { shot: "Sitting with chai, talking to camera", how: "Eye level, window light on face", secs: 8 },
      { shot: "Old family photo / wedding photo on shelf", how: "Slow zoom-in", secs: 3 },
      { shot: "Hands kneading dough or chopping", how: "Over-the-shoulder shot", secs: 5 },
    ],
    voice: [
      "Har koi kehta tha — 'isse accha khana bahar nahi milta.'",
      "Toh maine socha… ghar se hi shuru karti hoon.",
      "Aaj mere ghar se hi, poore Ghansoli ko ghar ka khana milta hai.",
    ],
    cta: "Order your first thali — link in bio.",
  },
  {
    day: 3,
    title: "Kitchen tour — where your food is made",
    hook: "Aaj dikhaungi woh kitchen jahan aapka khana banta hai.",
    why: "Transparency builds trust before the first order.",
    scenes: [
      { shot: "Wide shot of full kitchen", how: "Stand at the door, slow pan left to right", secs: 5 },
      { shot: "Stove with 2-3 sabzis cooking", how: "Close-up, steam visible", secs: 4 },
      { shot: "Utensil shelf / steel dabbas", how: "Pan across shelves", secs: 4 },
      { shot: "Fridge + storage area", how: "Open and show clean storage", secs: 4 },
    ],
    voice: [
      "Yeh hai mera kitchen — saaf, sundar aur sab kuch ghar ka.",
      "Jo aap khate ho, yahin banta hai — apne haathon se.",
    ],
    cta: "Would you eat from this kitchen every day? Tell me in comments.",
  },
  {
    day: 4,
    title: "My masala dabba — 20 years of flavour",
    hook: "Meri masala dabba meri saas se mili thi… 20 saal purani hai.",
    why: "Heritage + close-up visuals = highly saveable content.",
    scenes: [
      { shot: "Opening the masala dabba lid", how: "Top-down shot, good light", secs: 4 },
      { shot: "Each katori of masala one by one", how: "Slow pan over compartments", secs: 6 },
      { shot: "Pinching and rubbing haldi/garam masala", how: "Extreme close-up of fingers", secs: 4 },
      { shot: "Sprinkling masala into a pot", how: "Action shot with steam", secs: 3 },
    ],
    voice: [
      "Har masala ki apni kahani hai — koi bazaar ka nahi, sab ghar ka pisa hua.",
      "Isi dabbe se aata hai woh taste jo aap 'ghar jaisa' bolte ho.",
    ],
    cta: "Which masala do you think is my secret? Guess below 👇",
  },
  {
    day: 5,
    title: "4:30 AM — a day in my life",
    hook: "Jab aap so rahe hote ho, meri chulha jal chuki hoti hai.",
    why: "Day-in-the-life is the backbone of small-business content.",
    scenes: [
      { shot: "Alarm clock / dark window", how: "Static shot, low light is fine", secs: 3 },
      { shot: "You lighting the stove, filling water", how: "Normal light now, follow the routine", secs: 5 },
      { shot: "Cutting vegetables — big pile", how: "Top-down on the chopping board", secs: 5 },
      { shot: "Pressure cooker whistling", how: "Close-up, let the whistle sound play", secs: 4 },
      { shot: "First thali of the day ready", how: "Slow circle around the plate", secs: 5 },
    ],
    voice: [
      "Subah 4:30 baje alarm… aur din shuru.",
      "Sabzi, dal, rotiyan — sab taaza, tabhi banta hai jab aap neend mein ho.",
      "Kyunki ghar ka khana wait nahi karta, aur main bhi nahi.",
    ],
    cta: "Respect the 4 AM club 🙏 Follow for daily kitchen life.",
  },
  {
    day: 6,
    title: "Meet my family — my kitchen staff",
    hook: "Meri staff? Mera pati, meri beti, aur meri saas.",
    why: "Family cameos humanise the brand and get shared.",
    scenes: [
      { shot: "Family member helping — stirring/tasting", how: "Candid, don't pose them", secs: 5 },
      { shot: "Someone tasting food and giving thumbs up", how: "Close-up on reaction", secs: 4 },
      { shot: "Everyone laughing in the kitchen", how: "Wide shot, natural moment", secs: 4 },
    ],
    voice: [
      "Yeh hai meri poori team — bina salary ke, sirf pyaar se kaam karti hai.",
      "Ghar ka khana ghar ke logon se banta hai, employees se nahi.",
    ],
    cta: "Tag the family member who is the real head chef of your house 😄",
  },
  {
    day: 7,
    title: "Plating my signature thali",
    hook: "Yeh thali dekh ke aap bhi bhookh lag jaayegi.",
    why: "Pure food beauty — the follow-worthy shot that sells the menu.",
    scenes: [
      { shot: "Empty steel thali placed on table", how: "Top-down, clean background", secs: 3 },
      { shot: "Serving rice, then dal, then sabzi", how: "Top-down, one by one", secs: 8 },
      { shot: "Rotis being placed in the casserole", how: "Slightly angled", secs: 4 },
      { shot: "Final thali with garnish + ghee drizzle", how: "Slow push-in on the full plate", secs: 5 },
    ],
    voice: [
      "Dal, chawal, roti, sabzi, salad — poora poshan, poora pyaar.",
      "Ghar ka thali, restaurant ke feel ke saath.",
    ],
    cta: "Order this thali today — link in bio.",
  },
  {
    day: 8,
    title: "Cooking timelapse — raw to thali in 20 seconds",
    hook: "20 second mein dikhaata hoon mera poora din.",
    why: "Timelapses are the highest-retention food format.",
    scenes: [
      { shot: "Phone fixed on tripod, whole cooking session", how: "Time-lapse mode, top-down or side angle, 2-3 hrs", secs: 15 },
      { shot: "Final plate placed in frame at the end", how: "Normal speed for last 3 sec", secs: 3 },
    ],
    voice: [
      "4 ghante ka mehnat, 20 second mein.",
      "Har thali ke peeche yehi process hai — har din.",
    ],
    cta: "Which dish should I timelapse next? Comment 👇",
  },
  {
    day: 9,
    title: "Market fresh — my morning sabzi run",
    hook: "Meri sabzi aaj subha 6 baze bazar se aayi hai.",
    why: "Ingredient sourcing = quality proof customers love.",
    scenes: [
      { shot: "Walking into the market with bag", how: "Follow shot from behind", secs: 4 },
      { shot: "Picking tomatoes/greens, checking freshness", how: "Close-up on hands selecting", secs: 5 },
      { shot: "Full bag of vegetables", how: "Hold it up to camera, smile", secs: 3 },
      { shot: "Washing vegetables at home", how: "Water running, close-up", secs: 4 },
    ],
    voice: [
      "Jo sabzi main ghar mein nahi khilaungi, woh aapko kaise dungi?",
      "Roz subah, roz taaza — yehi mera usool hai.",
    ],
    cta: "Fresh is non-negotiable. Order today!",
  },
  {
    day: 10,
    title: "ASMR — the sounds of my kitchen",
    hook: "Sound on karo… yeh awaazein sunke bhookh lagegi.",
    why: "ASMR cooking reels get huge reach — no talking needed.",
    scenes: [
      { shot: "Chopping vegetables rhythm", how: "Very close mic, top-down", secs: 5 },
      { shot: "Tadka — mustard seeds crackling in oil", how: "Close-up, CLEAR audio", secs: 5 },
      { shot: "Roti phoolti hui on tawa", how: "Side angle", secs: 4 },
      { shot: "Pressure cooker whistle", how: "Any angle, let it whistle", secs: 3 },
      { shot: "Serving spoon scraping the pot", how: "Close-up", secs: 3 },
    ],
    voice: [],
    cta: "No voice needed — just sound. Which sound was your favourite? 👇",
  },
  {
    day: 11,
    title: "Signature dish teaser — can you name it?",
    hook: "3 clues… dish ka naam batao.",
    why: "Interactive guessing hooks drive comments (algorithm fuel).",
    scenes: [
      { shot: "Clue 1: main ingredient raw", how: "Close-up mystery shot", secs: 3 },
      { shot: "Clue 2: masala going in", how: "Partial view, hide the pot", secs: 3 },
      { shot: "Clue 3: final dish half-covered", how: "Tease without revealing", secs: 3 },
      { shot: "Reveal: full dish", how: "Quick reveal + your smile", secs: 3 },
    ],
    voice: [
      "Hint 1… hint 2… hint 3…",
      "Naam batao comments mein — pehle 10 sahi jawab ko special reply!",
    ],
    cta: "Comment your guess 👇",
  },
  {
    day: 12,
    title: "Homemade ghee / masala — the secret step",
    hook: "Yeh cheez store-bought kabhi nahi ho sakti.",
    why: "Process content proves the 'just like home' promise.",
    scenes: [
      { shot: "Raw material — cream/spices laid out", how: "Flat lay top-down", secs: 4 },
      { shot: "The process — churning/roasting/grinding", how: "Close-up on the action", secs: 8 },
      { shot: "Final product in a jar", how: "Golden light if possible", secs: 4 },
      { shot: "Adding it to the dish", how: "Drizzle/sprinkle shot", secs: 3 },
    ],
    voice: [
      "Do din ka process, ek chhota sa jar — par taste poora badal deta hai.",
      "Isliye mera khana 'alag' lagta hai.",
    ],
    cta: "Want this in your thali? Order via Homatri.",
  },
  {
    day: 13,
    title: "Roti rolling — 60 rotis, one session",
    hook: "Ek ghante mein 60 rotiyan — dekho kaise.",
    why: "Skill display + volume = mesmerising, high-share content.",
    scenes: [
      { shot: "Dough ball being rolled flat", how: "Top-down on the chakla", secs: 5 },
      { shot: "Roti puffing on the tawa", how: "Side angle at flame level", secs: 5 },
      { shot: "Stack of finished rotis growing", how: "Same angle, watch the stack rise", secs: 6 },
      { shot: "You wiping forehead, smiling at camera", how: "Candid end shot", secs: 3 },
    ],
    voice: [
      "Ek thali mein do roti… aaj ke order ke liye saatavan bhi nahi hai.",
      "Haath thak jaate hain, par mann nahi.",
    ],
    cta: "Respect the roti hands 🙌 Follow for more.",
  },
  {
    day: 14,
    title: "Sunday prep — my weekly masala & bases",
    hook: "Sunday ko main aaram nahi karti… main prepare karti hoon.",
    why: "Shows the systems behind consistency — business-minded content.",
    scenes: [
      { shot: "All empty containers in a row", how: "Wide shot of workspace", secs: 3 },
      { shot: "Roasting and grinding big masala batch", how: "Mix of close-ups", secs: 8 },
      { shot: "Filling and labelling each jar", how: "Close-up on labels", secs: 5 },
      { shot: "Full shelf of prepared jars", how: "Proud final reveal", secs: 4 },
    ],
    voice: [
      "Ek hafte ka swaad, ek Sunday ki mehnat.",
      "Isliye har thali ek jaisa perfect aata hai — recipe nahi, system.",
    ],
    cta: "Consistency is my recipe. Order any day!",
  },
  {
    day: 15,
    title: "My kitchen cleaning routine",
    hook: "Khane se pehle — safai ka round.",
    why: "Hygiene proof — the #1 objection for home kitchens, killed visually.",
    scenes: [
      { shot: "Wiping counters and stove", how: "Before/after style", secs: 5 },
      { shot: "Washing utensils in hot water", how: "Steam + bubbles close-up", secs: 5 },
      { shot: "Sanitising tiffin boxes", how: "Show each box being cleaned", secs: 5 },
      { shot: "Final clean kitchen wide shot", how: "Same angle as Day 3 for contrast", secs: 4 },
    ],
    voice: [
      "Mere ghar mein jo banta hai, wahi aapke ghar jaata hai.",
      "Isliye safai mere liye ibaadat jaisa hai — roz, har baar.",
    ],
    cta: "100% hygiene, 100% home. That's the Homatri promise.",
  },
  {
    day: 16,
    title: "Packing time — sealing your tiffin",
    hook: "Aapka khana kaise pack hota hai? Aaj dikhaungi.",
    why: "Packaging unboxing is proven cloud-kitchen content.",
    scenes: [
      { shot: "Empty tiffin boxes in a row", how: "Top-down", secs: 3 },
      { shot: "Filling each section with food", how: "Top-down, assembly line style", secs: 8 },
      { shot: "Sealing with the lid + label sticker", how: "Close-up on the seal click", secs: 4 },
      { shot: "Stack of packed, sealed tiffins", how: "Final hero shot", secs: 4 },
    ],
    voice: [
      "Sealed pack, saaf haathon se, seedha aapke door tak.",
      "Jaise maa pack kare waise — dhyaan se.",
    ],
    cta: "Your tiffin is sealed with care. Order on Homatri.",
  },
  {
    day: 17,
    title: "What's in my delivery bag?",
    hook: "Aaj ke delivery bag mein kya hai? Let's unpack.",
    why: "Unboxing format + order preview converts viewers to buyers.",
    scenes: [
      { shot: "The delivery bag closed on table", how: "Tap the bag to open", secs: 3 },
      { shot: "Taking out tiffins one by one", how: "Over the bag, top-down", secs: 6 },
      { shot: "Opening one tiffin to show food", how: "Lid lift reveal, steam if any", secs: 5 },
      { shot: "Note/receipt if any + smile", how: "Hold up to camera", secs: 3 },
    ],
    voice: [
      "Aaj chale gaye [number] tiffin — har ek ek ghar, ek kahani.",
      "Agle tiffin mein aapka naam hona chahiye!",
    ],
    cta: "Order now — tomorrow's bag could be yours.",
  },
  {
    day: 18,
    title: "Stove to door — the delivery handoff",
    hook: "Mere haathon se… rider ke haathon… aapke ghar tak.",
    why: "Showing the last mile removes delivery doubts.",
    scenes: [
      { shot: "Packed tiffins ready at door", how: "Static shot", secs: 3 },
      { shot: "Rider arriving / picking up bag", how: "Candid from doorway", secs: 5 },
      { shot: "Rider leaving on two-wheeler", how: "From gate or window", secs: 4 },
      { shot: "You waving goodbye", how: "Casual end", secs: 3 },
    ],
    voice: [
      "Mera kaam khana banane tak hai… aapke tak pahunchana Homatri karta hai.",
      "Ek hi sheher, ek hi pariwar ab.",
    ],
    cta: "Track your tiffin live on the Homatri app.",
  },
  {
    day: 19,
    title: "Guess the ingredient — zoom challenge",
    hook: "Aankhein tez karo — yeh kya hai?",
    why: "Micro-guessing games are comment magnets.",
    scenes: [
      { shot: "Extreme close-up of a texture (grated coconut?)", how: "Very zoomed, mysterious", secs: 3 },
      { shot: "Another close-up (spice powder?)", how: "Blur the background", secs: 3 },
      { shot: "One more (curd? ghee?)", how: "Macro-style", secs: 3 },
      { shot: "Zoom out reveal of all three", how: "Pull back slowly", secs: 4 },
    ],
    voice: [
      "Ek wala sahi jawab… toh next reel mein aapka naam!",
    ],
    cta: "Answers in comments — no cheating!",
  },
  {
    day: 20,
    title: "Customer love — first reactions",
    hook: "Jab customer pehli baar khana kholta hai… woh chehre dekhne layak hoti hai.",
    why: "Social proof is the strongest conversion content.",
    scenes: [
      { shot: "WhatsApp reviews screenshot", how: "Screen record scrolling the chats", secs: 6 },
      { shot: "You reading a review, smiling", how: "Phone in hand, face visible", secs: 5 },
      { shot: "Packing the next order with extra energy", how: "Candid kitchen shot", secs: 4 },
    ],
    voice: [
      "Yeh messages hi meri salary hai.",
      "Aapka ek 'thank you didi' — poora din ban jaata hai.",
    ],
    cta: "Order once — review karna mat bhoolna ❤️",
  },
  {
    day: 21,
    title: "50 rotis, 30 orders — inside a big batch",
    hook: "Aaj ka order dekh ke mera bhi dil dhak-dhak.",
    why: "Volume day = drama + pride; great retention.",
    scenes: [
      { shot: "Order list on phone", how: "Over-the-shoulder", secs: 3 },
      { shot: "Big kadhai of sabzi being stirred", how: "Two hands on the spoon — show scale", secs: 5 },
      { shot: "Assembly line of tiffins being filled", how: "Side angle, repeated motion", secs: 6 },
      { shot: "Final count — all tiffins in rows", how: "Wide hero shot", secs: 4 },
    ],
    voice: [
      "Jab order zyada aate hain, mera dil khush… aur haath thode thakeele.",
      "Par har tiffin, pehle jaisa hi dhyaan se.",
    ],
    cta: "Big batch days need big love. Follow the journey!",
  },
  {
    day: 22,
    title: "Business update — what I earned & learned",
    hook: "Pehle mahine ka sach — kitna kamaya, kya seekha.",
    why: "Revenue transparency is the most-saved small-business content.",
    scenes: [
      { shot: "You sitting with notebook/phone", how: "Serious face, then smile", secs: 5 },
      { shot: "Orders count / earnings app screen", how: "Screen record, hide personal info", secs: 5 },
      { shot: "One lesson written on paper", how: "Hold it up to camera", secs: 4 },
    ],
    voice: [
      "Mahina ek: [X] orders, [Y] smiley customers, aur ek badi seekh —",
      "consistency hi asli marketing hai.",
      "Agla mahina aur bada… aap ke saath.",
    ],
    cta: "Building in public — follow the numbers with me.",
  },
  {
    day: 23,
    title: "The struggle is real — 4:30 AM truths",
    hook: "Har din aisa nahi hota ki sab perfect jaaye.",
    why: "Vulnerability balances the highlight reel — deep connection.",
    scenes: [
      { shot: "Tired you, sitting with chai", how: "Quiet, honest framing", secs: 6 },
      { shot: "A sabzi that got burnt / extra salty", how: "Show the mistake honestly", secs: 4 },
      { shot: "Making it right — fresh batch", how: "Action restart shot", secs: 5 },
      { shot: "Final smile — 'hum haar nahi maante'", how: "Eye contact with camera", secs: 3 },
    ],
    voice: [
      "Kuch din mushkil hote hain… gala baith jaata hai, thakan hoti hai.",
      "Par jo ghar ka khana banata hai, woh haar nahi maanta.",
    ],
    cta: "Respect to every home cook grinding daily 🙏",
  },
  {
    day: 24,
    title: "My biggest mistake + how I fixed it",
    hook: "Maine galti ki… aur sach batati hoon.",
    why: "Mistake stories out-perform perfect content on trust.",
    scenes: [
      { shot: "Talking to camera, honest tone", how: "Static, close framing", secs: 8 },
      { shot: "Show the fix — new process/tool", how: "Demonstrate the change", secs: 6 },
      { shot: "Result — happy customer message", how: "Screen or note", secs: 4 },
    ],
    voice: [
      "Galti sab se hoti hai… asli baat hai sudhaar.",
      "Aaj mera kitchen kal se behtar hai — yehi growth hai.",
    ],
    cta: "What should I improve next? Comment honestly 👇",
  },
  {
    day: 25,
    title: "Q&A — aapke sawaal, mere jawaab",
    hook: "Aapne pucha tha… aaj jawaab dungi.",
    why: "Answering comments makes followers feel seen and boosts engagement.",
    scenes: [
      { shot: "Question 1 screenshot + your answer", how: "Split screen or cut between", secs: 6 },
      { shot: "Question 2 + answer", how: "Same pattern", secs: 6 },
      { shot: "Question 3 + answer", how: "Same pattern", secs: 6 },
    ],
    voice: [
      "Aapke sawaalon se hi main agla reel banati hoon — puchte raho!",
    ],
    cta: "Drop your question for the next Q&A 👇",
  },
  {
    day: 26,
    title: "My regulars — the family that orders daily",
    hook: "Ek family 30 din se roz order karti hai… yeh unki kahani hai.",
    why: "Loyalty stories show product-market fit better than any ad.",
    scenes: [
      { shot: "Order history on app (regulars)", how: "Screen record, hide numbers", secs: 5 },
      { shot: "Packing their usual order with a small extra", how: "Add a handwritten note!", secs: 6 },
      { shot: "Sealing the tiffin with the note", how: "Close-up on the note", secs: 3 },
    ],
    voice: [
      "Roz ka customer woh hota hai jo ghar ka hissa ban jaata hai.",
      "Aapke liye ek chhota sa surprise aaj ke tiffin mein 💛",
    ],
    cta: "Become a regular — order daily tiffin plans on Homatri.",
  },
  {
    day: 27,
    title: "Festival special — food & tradition",
    hook: "[Festival] mein hum yeh banate hain — ghar mein, aise.",
    why: "Festive content rides seasonal search and emotion.",
    scenes: [
      { shot: "Festival decorations at home", how: "Warm wide shot", secs: 4 },
      { shot: "Special dish being prepared", how: "Close-up on the special steps", secs: 8 },
      { shot: "Family eating together", how: "Candid table shot", secs: 5 },
    ],
    voice: [
      "Tyohaar aur khana — dono ghar ke bolte hain.",
      "Is baar, thoda hi sahi… aapke ghar bhi humara tyohaar pahunche.",
    ],
    cta: "Festival special menu on Homatri — book now!",
  },
  {
    day: 28,
    title: "My dream — where this kitchen goes",
    hook: "Aaj 20 tiffin… kal 200. Sapne dekho toh bade.",
    why: "Vision content turns followers into invested well-wishers.",
    scenes: [
      { shot: "Looking out the window thoughtfully", how: "Cinematic, soft light", secs: 4 },
      { shot: "Your hands working — the engine of the dream", how: "Close-up montage", secs: 5 },
      { shot: "Talking straight to camera about your dream", how: "Steady, sincere", secs: 8 },
      { shot: "Smile + kitchen behind you", how: "Wide final frame", secs: 3 },
    ],
    voice: [
      "Mera sapna: mera khana, sheher ke har ghar tak.",
      "Aap support karte raho… main banati rahungi.",
    ],
    cta: "Be part of the journey — follow & order.",
  },
  {
    day: 29,
    title: "Bloopers — jab kitchen mein sab gadbad",
    hook: "Perfect reels ke peeche yeh sachai hai 😂",
    why: "Bloopers are the most shared/human content type.",
    scenes: [
      { shot: "Any failed take — dropped lid, flour spill", how: "Keep camera rolling ALWAYS on shoot days", secs: 4 },
      { shot: "Roti flying off the tawa", how: "Candid accident shots", secs: 3 },
      { shot: "You laughing at yourself", how: "Natural laughter, best ending", secs: 4 },
    ],
    voice: [
      "Yeh wahi clips hain jo main post nahi karti… aaj kar rahi hoon 😄",
    ],
    cta: "Follow for the real, unfiltered kitchen life.",
  },
  {
    day: 30,
    title: "30 days done — thank you + what's next",
    hook: "30 din pehle koi nahi jaanta tha mujhe. Aaj…",
    why: "Milestone recaps convert casual viewers into community.",
    scenes: [
      { shot: "Day 1 clip flashback (reuse best frame)", how: "Contrast with today", secs: 3 },
      { shot: "Today — you + full tiffin setup", how: "Confident hero shot", secs: 5 },
      { shot: "Numbers: orders, smiles, followers", how: "Text overlays do the talking", secs: 5 },
      { shot: "Deep bow / namaste to camera", how: "Gratitude frame", secs: 4 },
    ],
    voice: [
      "30 din, [X] tiffin, aur hazaaron pyaar — shukriya.",
      "Yeh toh shuruaat hai. Ab dekho agla 30.",
    ],
    cta: "Thank you for 30 days of love ❤️ Keep ordering on Homatri.",
  },
];

export const TOTAL_CONTENT_DAYS = CONTENT_PLAN.length;
